In [2]:
import pandas as pd
import numpy as np
import requests
import json
import ast
from pycoingecko import CoinGeckoAPI

df_polka = pd.read_json("polkadot max.json")


df_polka["prices"] = df_polka["prices"].astype(str)
df_polka["market_caps"] = df_polka["market_caps"].astype(str)
df_polka["total_volumes"] = df_polka["total_volumes"].astype(str)

df_polka["unix_timestamp"] = df_polka["prices"].apply(lambda x: int(x.split(", ")[0][1:]))
df_polka["date"] = pd.to_datetime(df_polka["unix_timestamp"], unit="ms")
df_polka.head(10)

df_polka["prices"] = df_polka["prices"].apply(ast.literal_eval)
df_polka["market_caps"] = df_polka["market_caps"].apply(ast.literal_eval)
df_polka["total_volumes"] = df_polka["total_volumes"].apply(ast.literal_eval)

def remove_unix_timestamp(entry):
    return entry[1]

df_polka["prices"] = df_polka["prices"].apply(remove_unix_timestamp)
df_polka["market_caps"] = df_polka["market_caps"].apply(remove_unix_timestamp)
df_polka["total_volumes"] = df_polka["total_volumes"].apply(remove_unix_timestamp)

df_polka = df_polka.drop(columns=['unix_timestamp'])

pd.set_option('display.float_format', '{:.2f}'.format)
pd.options.display.float_format = '{:.15f}'.format
df_polka['year'] = df_polka['date'].dt.year
df_polka.head(10)

,prices,market_caps,total_volumes,date,year
0,2.936700000000000,0.000000000000000,82413981.296811223030090,2020-08-19,2020
1,2.936700000000000,0.000000000000000,82413981.296811223030090,2020-08-20,2020
2,2.898800000000000,0.000000000000000,49511744.884639158844948,2020-08-21,2020
3,2.871900000000000,0.000000000000000,51233752.827103465795517,2020-08-22,2020
4,4.481400000000000,4028277492.388105392456055,473920951.291182100772858,2020-08-23,2020
5,3.966100000000000,3630430965.686846256256104,335685225.448210418224335,2020-08-24,2020
6,4.576900000000000,4162344881.701516628265381,395502571.898960709571838,2020-08-25,2020
7,5.493900000000000,4910960800.054019927978516,729611892.217291951179504,2020-08-26,2020
8,6.067700000000000,5508438431.636098861694336,853376793.311736226081848,2020-08-27,2020
9,5.638500000000001,5147685413.841153144836426,995432623.197182059288025,2020-08-28,2020

In [3]:
archivo_csv = "Polkadot_DF.csv"
df_polka.to_csv(archivo_csv, index=False)